-- Seed calendar_events from legacy calendarData.js
-- Run after calendar_events.sql. Truncates existing rows.
truncate public.calendar_events cascade;
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Exhibición Inicio Tempada', '¡Damos inicio á tempada 2025-2026!', 'Non vos perdades a exhibición de inicio de tempada das nosas ximnastas no Pavillón de Cabanas Salcedo.', '2025-09-12', NULL, 'ritmica', NULL, 'Pavillón de Cabanas Salcedo', '/images/icons/rit.png', NULL, NULL, 'Lola Costa, Carlota Mariño, Alba Agra, Inés Nogueira, Edurne Dorado, Alejandra Meijueiro, Alba Navarro e os dous Conxuntos Xuvenil Base.');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Torneo Milenium', 'VII Troeno Nacional Club Rítmica Milenium', 'No Palacio de Deportes de Riazor en A Coruña o 20 de Setembro.', '2025-09-20', NULL, 'ritmica', NULL, 'Palacio de Deportes de Riazor, A Coruña', '/images/events/milenium.png', 'https://www.visitcoruna.com/turismo/es/que-hacer-en-a-coruna/naturaleza-y-deporte/agenda-deportiva/evento-deportivo-detalle/vii-torneo-nacional-club-ritmica-milenium/suceso/1453901429562?argIdioma=en', NULL, 'Lola Costa, Carlota Mariño, Alba Agra, Inés Nogueira, Edurne Dorado, Alejandra Meijueiro, Alba Navarro e os dous Conxuntos Xuvenil Base.');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Torneo Valoe', 'Torneo Valoe', 'En Avilés o 27 de Setembro.', '2025-09-27', NULL, 'ritmica', NULL, 'Avilés', '/images/icons/rit.png', 'https://www.facebook.com/p/Club-Escuela-Asturiana-de-Gimnasia-R%C3%ADtmica-Valoe-61572564407438/', NULL, 'Lola Costa, Carlota Mariño, Alba Agra, Inés Nogueira, Edurne Dorado, Alejandra Meijueiro e os dous Conxuntos Xuvenil Base.');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('ED Caldas de Reis', 'Damos comezo ás Escolas Deportivas en Caldas de Reis!', 'Ás 16:30 no Pavilllón Deportivo Municipal e Caldas!', '2025-10-01', NULL, NULL, 'ED Caldas de Reis', 'Pavillón Deportivo Municipal, Caldas de Reis', '/images/events/escolas-caldas.jpeg', 'https://www.escolasdeportivastreboada.com/caldas.html', NULL, NULL);
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('EDM Pontevedra', 'Damos comezo ás Escolas Deportivas Municipais en Pontevedra!', 'Ás 18:00 no Pavilón Municipal dos Deportes de Pontevedra!', '2025-10-02', NULL, NULL, 'EDM Pontevedra', 'Pavillón Municipal dos Deportes de Pontevedra', '/images/events/inicio-escolas.jpeg', 'https://www.escolasdeportivastreboada.com/pontevedra.html', NULL, NULL);
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('IV Torneo Open Treboada', '¡No os perdáis la IV edición del Torneo Open Treboada de Gimnasia Rítmica que organizamos en el Pabellón Municipal de los Deportes!', NULL, '2025-10-04', NULL, 'ritmica', 'Club Treboada', 'Pabellón Municipal de los Deportes, Pontevedra', '/images/events/IV-torneo-rit.jpg', 'https://clubtreboada.es/torneo-treboada.html', NULL, NULL);
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('EDM Soutomaior', 'Damos comezo ás Escolas Deportivas Municipais en Soutomaior!', 'Ás 16:30 no Pavillón da Montesiña!', '2025-10-07', NULL, NULL, 'EDM Soutomaior', 'Pavillón da Montesiña, Soutomaior', '/images/events/soutomaior2.png', 'https://www.escolasdeportivastreboada.com/soutomaior.html', NULL, NULL);
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Copa Atlántica', 'Copa Atlántica de Ximansia Rítmica', 'Domingo 5 de Outubro en xornada de mañá en Lalín.', '2025-10-05', NULL, 'ritmica', NULL, 'Lalín', '/images/events/copa-atlantica.jpeg', 'https://www.instagram.com/copaatlantica', NULL, 'Alejandra Meijueiro, Alba Navarro, Edurne Dorado, Inés Nogueira, Alba Agra, Carlota Mariño, Lola Costa e os dous Conxuntos Xuvenil Base');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Copa e Campionato Galego', 'Control Copa Base Individual e Campionato Gallego de Base de Conxuntos', 'Sábado 18 de Outubro no Pavillón dos Remedios en Ourense.', '2025-10-18', NULL, 'ritmica', NULL, 'Pavillón dos Remedios, Ourense', '/images/events/gallego-oct.jpg', 'https://www.ximnasia.com/campionato/campionato-galego-base-conxuntos-xunta-de-galicia-control-copa-base-individual-e-3-fase-copa-conxuntos-xr.html', NULL, 'Alejandra Meijueiro, Alba Navarro, Edurne Dorado, Inés Nogueira, Alba Agra, Carlota Mariño, Lola Costa e os dous Conxuntos Xuvenil Base');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('IV Torneo Viravolta Jael', 'IV Torneo V Gala Internacional VIRAVOLTA JAEL', 'Os días 25 e 26 de Outubro no Multiusos Fontes do Sar en Santiago de Compostela', '2025-10-25', '2025-10-27', 'ritmica', NULL, 'Multiusos Fontes do Sar, Santiago de Compostela', '/images/events/torneo-viravolta.jpeg', 'https://clubviravoltasantiago.com/torneo-de-gimnasia-ritmica/', NULL, 'Alba Navarro, Edurne Dorado, Alba Agra, Inés Nogueira, Carlota Mariño, Alejandra Meijueiro e os dous Conxuntos Xuvenil Base');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Campeonato Nacional de Conjuntos Base', 'Campeonato Nacional de Conjuntos Base', 'Del 21 al 23 de Noviembre en Castellón', '2025-11-21', '2025-11-24', 'ritmica', NULL, 'Castellón', '/images/icons/rit.png', 'https://rfegimnasia.es/especialidades/calendario/Especialidad/3', NULL, 'Conjunto Juvenil Base P y Conjunto Juvenil Base M');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Nacional Copa Base Individual', 'Nacional Copa Base Individual', 'Del 28 al 30 de Noviembre en Madrid', '2025-11-28', '2025-12-01', 'ritmica', NULL, 'Madrid', '/images/icons/rit.png', 'https://rfegimnasia.es/especialidades/calendario/Especialidad/3', NULL, NULL);
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Copa Galicia Acrobática', 'XVIII Copa Galicia Internacional Acrobática', 'Del 20 al 22 de Febrero en Vigo', '2026-02-20', '2026-02-23', 'acrobatica', NULL, 'Vigo', '/images/events/copa-galicia.jpg', 'https://www.ximnasia.com/nova/xviii-copa-galicia-internacional-de-gimnasia-acrobatica-v-trofeo-ciudad-de-vigo-2026.htm', NULL, 'Trío Youth, Trío Junior Base, Trío Cadete, Parella Cadete');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('MIAC ACRO', 'XX Maia International Acro Cup', 'Del 4 al 8 de Marzo en Maia, Portugal', '2026-03-04', '2026-03-09', 'acrobatica', NULL, 'Maia, Portugal', '/images/events/miac.webp', 'https://www.maiaacrocup.com/', NULL, 'Trío Youth, Parella Cadete');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('OPEN Madrid ACRO', 'Open Madrid Acro', 'Del 28 al 29 de Marzo en el Polideportivo Municipal de Moralzarzal', '2026-03-28', '2026-03-30', 'acrobatica', NULL, 'Polideportivo Municipal de Moralzarzal, Madrid', '/images/events/open-madrid-26.png', NULL, NULL, 'Grupo Autonómico e Grupo Nacional');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Copa Galicia ACRO', 'Copa Galicia Escolar e Base', '15 de Marzo en Gondomar.', '2026-03-15', '2026-03-16', 'acrobatica', NULL, 'Gondomar', '/images/icons/acro.png', NULL, NULL, 'Equipos Escolares e equipos Base Alevín Infantil e Cadete.');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Nacional ACRO', 'Campeonato Nacional y Base de Gimnasia Acrobática', 'Del 20 al 24 de Mayo de forma provisional sin sede asignada', '2026-05-20', '2026-05-25', 'acrobatica', NULL, 'Granada, pediente de confirmación', '/images/icons/acro.png', NULL, NULL, 'Grupo Nacional');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Galego ACRO', 'Campionato Galego e Campionato Galego Base de Ximnasia Acrobática', '25 de Abril en Nigrán', '2026-04-25', '2026-04-25', 'acrobatica', NULL, 'Nigrán', '/images/icons/acro.png', NULL, NULL, 'Grupos Autónomico e Nacional');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('Galego Escolar ACRO', 'Campionato Galego Escolar de Ximnasia Acrobática', NULL, '2026-06-20', '2026-06-20', 'acrobatica', NULL, 'Pontevedra', '/images/icons/acro.png', NULL, NULL, 'Grupos Escolar e Autonómico');
insert into public.calendar_events (title, subtitle, description, start_date, end_date, category, school, location, image_url, event_url, streaming_url, participate) values ('OPEN TREBOADA ACRO', 'OPEN TREBOADA CidadeDoLerez Ximnasia Acrobática', NULL, '2026-06-25', '2026-06-29', 'acrobatica', NULL, 'Pontevedra', '/images/open-acro/cartel.webp', NULL, NULL, 'Todos!');
